name: Release
on:
  push:
    tags:
      - 'v*'

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - run: cargo build --release && strip target/release/shorty && mv target/release/shorty target/release/shorty-linux
    - name: Release Linux
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/shorty-linux
        token: ${{ secrets.GH_TOKEN }}

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin
    - run: cargo build --release && strip target/release/shorty && mv target/release/shorty target/release/shorty-macos
    - name: Release macOS
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/shorty-macos
        token: ${{ secrets.GH_TOKEN }}

  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-pc-windows-msvc
    - run: cargo build --release
    - run: mv target/release/shorty.exe target/release/shorty-windows.exe
    - name: Release Windows
      uses: softprops/action-gh-release@v1
      with:
        files: target/release/shorty-windows.exe
        token: ${{ secrets.GH_TOKEN }}

